on:
  push:
    branches:
      - release
      - main
      - master
      - develop
    tags: ['*']

name: Website (pkgdown)

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          needs: website
          extra-packages: |
            pkgdown
            devtools

      - name: Roxygenize
        # The vignettes will be built in step "Deploy package"
        run: |
          devtools::document(roclets = c('rd', 'collate', 'namespace'))
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'

